name: nsio_flutter
description: A Flutter project templates for NonStopIO.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^0.1.3
  flutter_screenutil: ^2.3.1
  screen_loader: ^2.0.1

  #LOCAL-DATABASE
  shared_preferences: ^0.5.8

  #APP-DEVICE-INFO
  package_info: ^0.4.1

  #UTILS
  after_layout: ^1.0.7+2
  intl: 0.16.1

  #LOCATION
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.30

  dio: ^3.0.10
  geopoint: ^0.7.1
  android_intent: ^0.3.7+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
# To generate app icons run :  flutter pub run flutter_launcher_icons:main
# icon.png should be of ratio 1024X1024


flutter:
  uses-material-design: true

  #ASSETS
  assets:
    - assets/

  #FONTS
  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf